### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by anubisg1** [lxde/obconf-qt#2]
while trying to push the package in openSUSE:

Visit https://build.opensuse.org/request/show/260820

State of request 260820 was changed by babelworx:

  review -> declined

Comment:
  Numerous GPL-2.0+ licensed files. Check with upstream why this package has a LGPL-2.1+ COPYING and many files in src/ are GPL

Actions:
- submit X11:lxde/obconf-qt => openSUSE:Factory/obconf-qt

**Comment by jleclanche** [comment]
Urg

**Comment by PCMan** [comment]
It's my fault. It should be GNU GPL2 since it's derived from obconf, which is GPL'd.
I already fixed the COPYING and AUTHORS files.
