### ISSUE TITLE
usual build procedure doesn't consider desktop entry file

### ISSUE THREAD

**Issue by pmattern** [lxde/obconf-qt#6]
Compiling obconf-qt the usual way, namely
> mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DUSE_QT5=true ..
make

desktop entry file obconf-qt.desktop doesn't get built.

It's a regression since it used to get built in the not too distant past. Couldn't look into the details so far, though.

**Comment by jleclanche** [comment]
@luis-pereira can you help me with this?

**Comment by luis-pereira** [comment]
@jleclanche @pmattern done
